# Generated by Django 4.1.5 on 2023-03-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
