# Generated by Django 4.1.5 on 2023-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstatistics', '0002_alter_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamonmatch',
            name='score',
            field=models.IntegerField(db_column='Score', default=0),
        ),
    ]
