# Generated by Django 4.1.5 on 2023-03-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstatistics', '0003_alter_teamonmatch_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='date_foundation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.AddField(
            model_name='team',
            name='foundation_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.ForeignKey(blank=True, db_column='Team_type_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appstatistics.typeteam'),
        ),
    ]
